### ISSUE TITLE
Items Controller refactor

### ISSUE THREAD

**Issue by PlanetEfficacy** [PlanetEfficacy/little_shop#145]
```ruby
  def show
    @item = Item.find(params[:id])
    @review = Review.new
  end
```

Couldn't we do 

```ruby
  def show
    @item = Item.find(params[:id])
    @review = @item.reviews.new
  end  
```

Which would mean that we don't have to send the item id as a supplemental parameter?

**Comment by tgisg** [comment]
I tried this. Many things broke because the relationship between the new review and the item is created in the view. So if you try to do @review = @item.reviews.new it's like you're pre-emptively creating the relationship for something that does not yet exist. I think that makes sense? In any case I have opted not to change this or continue working on this in the interest of refactoring elsewhere.
