### ISSUE TITLE
Authenticated users security

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#47]
Background: An authenticated user 

      As an Authenticated User
      I cannot view another user's private data (current or past orders, etc)
      I cannot view the administrator screens or use admin functionality
      I cannot make myself an admin

**Comment by PlanetEfficacy** [comment]
I'm a little unclear on the meaning behind the second piece of functionality here, "I cannot view the administrator screens or use admin functionality."

Doesn't car "Admin User Dashboard" cover this with the features:   

As a registered user
  When I visit "/admin/dashboard"
  I get a 404

  As an unregistered user
  When I visit "/admin/dashboard"
  I get a 404

Currently these are our only admin paths. And  we are already testing that non admin get 404 pages when they try to visit this portion of the app.

**Comment by PlanetEfficacy** [comment]
@case-eee @s-espinosa @tgisg @kctrlv @susiirwin I ran into Carmer just now who clarified this card for me. As long as we are using strong_params we should be good for a user cannot make themselves an admin and he said there is not an automated way to test that beyond going to the page, opening the console, and making a new form field for role, and seeing what happens. Since we use strong_params, we should be good. Re the admin screens, he confirmed that it is possible we already have the functionality preventing non-admin from accessing the admin dashboard. We just need to be mindful that any future admin pages also need this authorization functionality. I think we handle that because we use a before action to authorize. That was a long way for me to say, this card is done.

**Comment by PlanetEfficacy** [comment]
@susiirwin @kctrlv @tgisg I did a PR, just needs review and merge. Thanks team!
