### ISSUE TITLE
.full_name method kicks up error when user clicks on view order

### ISSUE THREAD

**Issue by tgisg** [PlanetEfficacy/little_shop#75]

**Comment by tgisg** [comment]
Need to delete all cookies when using Fabricate in rails c! Not a bug, per se.

**Comment by tgisg** [comment]
We just need a place for these user profiles to be generated. As it is, you would have to make it in rails console.

**Comment by tgisg** [comment]
Tried creating a user profile for a user that is in my development database and it still kicks up the error

**Comment by tgisg** [comment]
Looks like user_profile is nil. It works if you do <h4><%= @order.user.username %></h4> it works. So somehow user_profile is not being associated with the user.

**Comment by PlanetEfficacy** [comment]
When you say it works, do you mean that it prints the user's username? We definitely want to iron out the ```.full_name``` method that @kctrlv  and I worked on yesterday in the ```user_profile ``` model. We didn't add functionality to create a user profile, because the card only said we need to see user info, not give users the ability to add interview. I agree that we should have that functionality down the line.

**Comment by tgisg** [comment]
@PlanetEfficacy It does print out the user's username. But we get a nil class error if we try to do user_profile.full_name
